import type { Plugin } from 'obsidian';
import { DEFAULT_SETTINGS } from '../constants';
import { SettingsService } from '../settings-service';

describe('SettingsService', () => {
  test('load falls back to defaults when stored data is invalid', async () => {
    const service = new SettingsService(createPluginMock('invalid payload'));
    await service.load();
    expect(service.getSnapshot()).toEqual(DEFAULT_SETTINGS);
  });

  test('getSnapshot returns a deep clone', async () => {
    const service = new SettingsService(createPluginMock({}));
    await service.load();

    const snapshot = service.getSnapshot();
    snapshot.exclusionListWords.push('mutated');
    snapshot.render.performanceMode = 'throttled';
    snapshot.filters.frequency.minCount = 99;
    snapshot.filters.scope.folderPaths?.push('some/path');
    snapshot.filters.frontmatterRules.push({
      key: 'status',
      operator: 'equals',
      value: 'done',
    });

    const after = service.getSnapshot();
    expect(after.exclusionListWords).not.toContain('mutated');
    expect(after.render.performanceMode).toBe(DEFAULT_SETTINGS.render.performanceMode);
    expect(after.filters.frequency.minCount).toBe(DEFAULT_SETTINGS.filters.frequency.minCount);
    expect(after.filters.scope.folderPaths).toEqual([]);
    expect(after.filters.frontmatterRules).toEqual([]);
  });

  test('updateFilters persists normalized values', async () => {
    const plugin = createPluginMock({
      exclusionListWords: ['  Alpha', 'alpha', ' ', 100],
    });
    const service = new SettingsService(plugin);

    await service.load();
    await service.updateFilters({
      includeTags: ['One', '#two', ''],
      excludeTags: ['#two', '#three'],
      frequency: {
        minCount: 100,
        maxCount: 2,
      },
    });

    expect(service.getSnapshot().exclusionListWords).toEqual(['alpha']);
    expect(plugin.saveData).toHaveBeenCalledTimes(1);
    expect(plugin.saveData).toHaveBeenCalledWith(
      expect.objectContaining({
        filters: expect.objectContaining({
          includeTags: ['#one', '#two'],
          excludeTags: ['#three'],
          frequency: {
            minCount: 2,
            maxCount: 100,
          },
        }),
      }),
    );
  });

  test('font family selection falls back to default when unsupported', () => {
    const service = new SettingsService(createPluginMock({}));
    expect(service.getSelectedSupportedFontFamily('serif')).toBe('serif');
    expect(service.getSelectedSupportedFontFamily('unsupported-font')).toBe(DEFAULT_SETTINGS.render.fontFamily);
  });

  test('font size updates enforce min/max constraints', async () => {
    const plugin = createPluginMock({});
    const service = new SettingsService(plugin);
    await service.load();

    const minResult = await service.updateMinimumFontSize(999);
    expect(minResult.minFontSize).toBe(64);
    expect(minResult.minFontSize).toBeLessThanOrEqual(minResult.maxFontSize);

    const maxResult = await service.updateMaximumFontSize(1);
    expect(maxResult.maxFontSize).toBe(64);
    expect(maxResult.maxFontSize).toBeGreaterThanOrEqual(maxResult.minFontSize);
    expect(plugin.saveData).toHaveBeenCalledTimes(2);
  });

  test('preview words are generated by the service', () => {
    const service = new SettingsService(createPluginMock({}));
    const previewWords = service.getSettingsPreviewWords();
    expect(previewWords.length).toBeGreaterThan(0);
    expect(previewWords[0]).toEqual(expect.objectContaining({ text: expect.any(String), size: expect.any(Number) }));
  });

  test('failed persistence does not mutate in-memory settings or emit change', async () => {
    const saveError = new Error('save failed');
    const plugin = createPluginMock({}, jest.fn().mockRejectedValue(saveError));
    const service = new SettingsService(plugin);
    const listener = jest.fn();

    await service.load();
    service.onChange(listener);
    const before = service.getSnapshot();

    await expect(service.updateRenderSettings({ performanceMode: 'throttled' })).rejects.toThrow('save failed');

    expect(service.getSnapshot()).toEqual(before);
    expect(listener).not.toHaveBeenCalled();
  });

  test('listener failures are isolated and do not fail updates', async () => {
    const service = new SettingsService(createPluginMock({}));
    const failingListener = jest.fn(() => {
      throw new Error('listener failed');
    });
    const healthyListener = jest.fn();

    const consoleSpy = jest.spyOn(console, 'error').mockImplementation(() => undefined);
    await service.load();
    service.onChange(failingListener);
    service.onChange(healthyListener);

    await expect(service.updateRenderSettings({ performanceMode: 'throttled' })).resolves.toBeUndefined();

    expect(failingListener).toHaveBeenCalledTimes(1);
    expect(healthyListener).toHaveBeenCalledTimes(1);
    expect(consoleSpy).toHaveBeenCalledWith('SettingsService listener failed', expect.any(Error));
    consoleSpy.mockRestore();
  });

  test('onChange unsubscribe stops future notifications', async () => {
    const service = new SettingsService(createPluginMock({}));
    const listener = jest.fn();
    await service.load();

    const unsubscribe = service.onChange(listener);
    await service.updateRenderSettings({ performanceMode: 'throttled' });
    unsubscribe();
    await service.updateRenderSettings({ performanceMode: 'balanced' });

    expect(listener).toHaveBeenCalledTimes(1);
  });
});

function createPluginMock(loadValue: unknown, saveDataMock?: jest.Mock): Plugin {
  return {
    loadData: jest.fn().mockResolvedValue(loadValue),
    saveData: saveDataMock ?? jest.fn().mockResolvedValue(undefined),
  } as unknown as Plugin;
}
