import type { Plugin } from 'obsidian';
import { DEFAULT_SETTINGS } from '@/settings/constants';
import { SettingsService } from '@/settings/settings-service';

describe('SettingsService', () => {
  test('load falls back to defaults when stored data is invalid', async () => {
    const service = new SettingsService(createPluginMock('invalid payload'));
    await service.load();
    expect(service.getSnapshot()).toEqual(DEFAULT_SETTINGS);
  });

  test('getSnapshot returns a deep clone', async () => {
    const service = new SettingsService(createPluginMock({}));
    await service.load();

    const snapshot = service.getSnapshot();
    snapshot.exclusionListWords.push('mutated');
    snapshot.render.performanceMode = 'throttled';
    snapshot.filters.frequency.minCount = 99;
    snapshot.filters.nlp.mode = 'aggressive';
    snapshot.filters.scope.folderPaths?.push('some/path');
    snapshot.filters.frontmatterRules.push({
      key: 'status',
      operator: 'equals',
      value: 'done',
    });

    const after = service.getSnapshot();
    expect(after.exclusionListWords).not.toContain('mutated');
    expect(after.render.performanceMode).toBe(DEFAULT_SETTINGS.render.performanceMode);
    expect(after.filters.frequency.minCount).toBe(DEFAULT_SETTINGS.filters.frequency.minCount);
    expect(after.filters.nlp.mode).toBe(DEFAULT_SETTINGS.filters.nlp.mode);
    expect(after.filters.scope.folderPaths).toEqual([]);
    expect(after.filters.frontmatterRules).toEqual([]);
  });

  test('updateFilters persists normalized values', async () => {
    const plugin = createPluginMock({
      exclusionListWords: ['  Alpha', 'alpha', ' ', 100],
    });
    const service = new SettingsService(plugin);

    await service.load();
    await service.updateFilters({
      includeTags: ['One', '#two', ''],
      excludeTags: ['#two', '#three'],
      minWordLength: 0,
      frequency: {
        minCount: 100,
        maxCount: 2,
      },
      nlp: {
        enabled: true,
        mode: 'aggressive',
        preserveAcronyms: true,
        minLemmaLength: 1,
        filterNumericTokens: true,
      },
    });

    expect(service.getSnapshot().exclusionListWords).toEqual(['alpha']);
    expect(plugin.saveData).toHaveBeenCalledTimes(1);
    expect(plugin.saveData).toHaveBeenCalledWith(
      expect.objectContaining({
        filters: expect.objectContaining({
          includeTags: ['#one', '#two'],
          excludeTags: ['#three'],
          minWordLength: 1,
          frequency: {
            minCount: 2,
            maxCount: 100,
          },
          nlp: {
            enabled: true,
            mode: 'aggressive',
            preserveAcronyms: true,
            minLemmaLength: 2,
            filterNumericTokens: true,
          },
        }),
      }),
    );
  });

  test('font family selection falls back to default when unsupported', () => {
    const service = new SettingsService(createPluginMock({}));
    expect(service.getSelectedSupportedFontFamily('serif')).toBe('serif');
    expect(service.getSelectedSupportedFontFamily(' serif ')).toBe('serif');
    expect(service.getSelectedSupportedFontFamily('unsupported-font')).toBe(DEFAULT_SETTINGS.render.fontFamily);
  });

  test('font size updates enforce min/max constraints', async () => {
    const plugin = createPluginMock({});
    const service = new SettingsService(plugin);
    await service.load();

    const minResult = await service.updateMinimumFontSize(999);
    expect(minResult.minFontSize).toBe(64);
    expect(minResult.minFontSize).toBeLessThanOrEqual(minResult.maxFontSize);

    const maxResult = await service.updateMaximumFontSize(1);
    expect(maxResult.maxFontSize).toBe(64);
    expect(maxResult.maxFontSize).toBeGreaterThanOrEqual(maxResult.minFontSize);
    expect(plugin.saveData).toHaveBeenCalledTimes(2);
  });

  test('preview words are generated by the service', () => {
    const service = new SettingsService(createPluginMock({}));
    const previewWords = service.getSettingsPreviewWords();
    expect(previewWords.length).toBeGreaterThan(0);
    expect(previewWords[0]).toEqual(expect.objectContaining({ text: expect.any(String), size: expect.any(Number) }));
  });

  test('getSupportedFontFamilyOptions returns supported entries', () => {
    const service = new SettingsService(createPluginMock({}));
    const options = service.getSupportedFontFamilyOptions();
    expect(options.length).toBeGreaterThan(0);
    expect(options).toContainEqual(expect.objectContaining({ value: 'sans-serif' }));
  });

  test('addExclusionListWord persists normalized, sorted values and rejects duplicates/blanks', async () => {
    const plugin = createPluginMock({ exclusionListWords: ['beta'] });
    const service = new SettingsService(plugin);
    await service.load();

    await expect(service.addExclusionListWord('  Alpha  ')).resolves.toBe(true);
    expect(service.getSnapshot().exclusionListWords).toEqual(['alpha', 'beta']);
    expect(plugin.saveData).toHaveBeenCalledTimes(1);

    await expect(service.addExclusionListWord('alpha')).resolves.toBe(false);
    await expect(service.addExclusionListWord('   ')).resolves.toBe(false);
    expect(plugin.saveData).toHaveBeenCalledTimes(1);
  });

  test('removeExclusionListWord normalizes input before removing', async () => {
    const plugin = createPluginMock({ exclusionListWords: ['alpha', 'beta'] });
    const service = new SettingsService(plugin);
    await service.load();

    await service.removeExclusionListWord('  ALPHA ');
    expect(service.getSnapshot().exclusionListWords).toEqual(['beta']);
    expect(plugin.saveData).toHaveBeenCalledTimes(1);
  });

  test('resetExclusionListWords restores sorted defaults', async () => {
    const plugin = createPluginMock({ exclusionListWords: ['custom-word'] });
    const service = new SettingsService(plugin);
    await service.load();

    await service.resetExclusionListWords();
    expect(service.getSnapshot().exclusionListWords).toEqual([...DEFAULT_SETTINGS.exclusionListWords].sort((a, b) => a.localeCompare(b)));
    expect(plugin.saveData).toHaveBeenCalledTimes(1);
  });

  test('getExclusionListSet returns normalized unique words', async () => {
    const service = new SettingsService(createPluginMock({
      exclusionListWords: ['  ALPHA ', 'alpha', '', ' beta '],
    }));
    await service.load();

    expect(service.getExclusionListSet()).toEqual(new Set(['alpha', 'beta']));
  });

  test('resetRenderSettings restores defaults and emits change', async () => {
    const service = new SettingsService(createPluginMock({}));
    const listener = jest.fn();
    await service.load();
    service.onChange(listener);

    await service.updateRenderSettings({ performanceMode: 'throttled', minFontSize: 22 });
    await service.resetRenderSettings();

    expect(service.getSnapshot().render).toEqual(DEFAULT_SETTINGS.render);
    expect(listener).toHaveBeenCalledTimes(2);
  });

  test('resetAllSettings restores all settings sections and emits change', async () => {
    const service = new SettingsService(createPluginMock({}));
    const listener = jest.fn();
    await service.load();
    service.onChange(listener);

    await service.updateRenderSettings({ performanceMode: 'throttled', minFontSize: 22 });
    await service.updateFilters({
      minWordLength: 9,
      includeTags: ['#project'],
    });
    await service.addExclusionListWord('custom-word');
    await service.resetAllSettings();

    expect(service.getSnapshot()).toEqual({
      ...DEFAULT_SETTINGS,
      exclusionListWords: [...DEFAULT_SETTINGS.exclusionListWords].sort((a, b) => a.localeCompare(b)),
    });
    expect(listener).toHaveBeenCalledTimes(4);
  });

  test('failed persistence does not mutate in-memory settings or emit change', async () => {
    const saveError = new Error('save failed');
    const plugin = createPluginMock({}, jest.fn().mockRejectedValue(saveError));
    const service = new SettingsService(plugin);
    const listener = jest.fn();

    await service.load();
    service.onChange(listener);
    const before = service.getSnapshot();

    await expect(service.updateRenderSettings({ performanceMode: 'throttled' })).rejects.toThrow('save failed');

    expect(service.getSnapshot()).toEqual(before);
    expect(listener).not.toHaveBeenCalled();
  });

  test('serializes concurrent render updates to avoid lost writes', async () => {
    const saveResolvers: Array<() => void> = [];
    const saveDataMock = jest.fn().mockImplementation(() => new Promise<void>((resolve) => {
      saveResolvers.push(resolve);
    }));
    const service = new SettingsService(createPluginMock({}, saveDataMock));
    await service.load();

    const first = service.updateRenderSettings({ performanceMode: 'throttled' });
    const second = service.updateRenderSettings({ wordPadding: 6 });

    await Promise.resolve();
    expect(saveDataMock).toHaveBeenCalledTimes(1);
    expect(saveDataMock).toHaveBeenNthCalledWith(
      1,
      expect.objectContaining({
        render: expect.objectContaining({
          performanceMode: 'throttled',
          wordPadding: DEFAULT_SETTINGS.render.wordPadding,
        }),
      }),
    );

    const resolveFirst = saveResolvers.shift();
    if (!resolveFirst) {
      throw new Error('Expected first save resolver');
    }
    resolveFirst();
    await first;
    await Promise.resolve();

    expect(saveDataMock).toHaveBeenCalledTimes(2);
    expect(saveDataMock).toHaveBeenNthCalledWith(
      2,
      expect.objectContaining({
        render: expect.objectContaining({
          performanceMode: 'throttled',
          wordPadding: 6,
        }),
      }),
    );

    const resolveSecond = saveResolvers.shift();
    if (!resolveSecond) {
      throw new Error('Expected second save resolver');
    }
    resolveSecond();
    await Promise.all([first, second]);

    expect(service.getSnapshot().render).toEqual(expect.objectContaining({
      performanceMode: 'throttled',
      wordPadding: 6,
    }));
  });

  test('listener failures are isolated and do not fail updates', async () => {
    const service = new SettingsService(createPluginMock({}));
    const failingListener = jest.fn(() => {
      throw new Error('listener failed');
    });
    const healthyListener = jest.fn();

    const consoleSpy = jest.spyOn(console, 'error').mockImplementation(() => undefined);
    await service.load();
    service.onChange(failingListener);
    service.onChange(healthyListener);

    await expect(service.updateRenderSettings({ performanceMode: 'throttled' })).resolves.toBeUndefined();

    expect(failingListener).toHaveBeenCalledTimes(1);
    expect(healthyListener).toHaveBeenCalledTimes(1);
    expect(consoleSpy).toHaveBeenCalledWith('SettingsService listener failed', expect.any(Error));
    consoleSpy.mockRestore();
  });

  test('onChange unsubscribe stops future notifications', async () => {
    const service = new SettingsService(createPluginMock({}));
    const listener = jest.fn();
    await service.load();

    const unsubscribe = service.onChange(listener);
    await service.updateRenderSettings({ performanceMode: 'throttled' });
    unsubscribe();
    await service.updateRenderSettings({ performanceMode: 'balanced' });

    expect(listener).toHaveBeenCalledTimes(1);
  });

  test('dispose removes listeners and suppresses future notifications', async () => {
    const service = new SettingsService(createPluginMock({}));
    const listener = jest.fn();
    await service.load();

    service.onChange(listener);
    service.dispose();
    await service.updateRenderSettings({ performanceMode: 'throttled' });

    expect(listener).not.toHaveBeenCalled();
  });
});

function createPluginMock(loadValue: unknown, saveDataMock?: jest.Mock): Plugin {
  return {
    loadData: jest.fn().mockResolvedValue(loadValue),
    saveData: saveDataMock ?? jest.fn().mockResolvedValue(undefined),
  } as unknown as Plugin;
}
